<?php
define("KEY","formacom");
define("COD","AES-128-ECB");
define("SERVIDOR","localhost");
define("USUARIO","root");
define("PASSWORD","");
define("BD","tiendapaypal");
define("CLIENTIDPAYPAL","AdfZo6m0qnNparPX5S_Q9ymLKJn1h-2B06CKB4i4nNHddwd8rQN7ORAz90tesaaQMXorRrcLCKJDe11a");
define("SECRETPAYPAL","EE1nGYRgPA8zpX9V97Ekz1wMmT4oe32WLcM5ask_KY5tEJmldv3_3mIDzR9Vaomj_yzOJjk-8NNqTZ8l");
?>